#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 14 14:51:58 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.7.1.zip
