#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 17 18:56:49 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.7.1.zip
